services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    volumes:
      - {{ project_dir }}/data:/var/lib/registry
      - {{ project_dir }}/auth:/auth
    restart: always

  registry-ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - "80:80"
    environment:
      - REGISTRY_TITLE=Mon Registry Docker
      - REGISTRY_URL=http://{{ registry_host_ip }}:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
    depends_on:
      - registry
    restart: always
